version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 20.17.0
    commands:
      - rm -rf /home/ubuntu/test/frontend-code/node_modules
      - rm -rf /home/ubuntu/test/frontend-code/build
      - npm install

  build:
    commands:
      - npm run build

artifacts:
  files:
    - '**/*'

