name: Build Docker Image on EC2

on:
  push:
    branches:
      - main  # Trigger the workflow on push to the main branch

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Checkout the code from the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Install SSH client
      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      # Step 3: Add SSH key and set permissions
      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key

      # Step 4: Add EC2 host to known_hosts to prevent SSH prompt
      - name: Add EC2 host to known_hosts
        env:
          AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
        run: |
          ssh-keyscan -H $AWS_EC2_HOST >> ~/.ssh/known_hosts

      # Step 5: SSH into EC2 instance, build Docker image, and push to Docker Hub
      - name: SSH and Build Docker Image on EC2
        env:
          AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
          AWS_EC2_HOST: ${{ secrets.AWS_EC2_HOST }}
          DOCKERHUB_USERNAME: ${{ secrets.DOCKERHUB_USERNAME }}
          DOCKERHUB_TOKEN: ${{ secrets.DOCKERHUB_TOKEN }}
        run: |
          ssh -i ~/.ssh/deploy_key $AWS_EC2_USER@$AWS_EC2_HOST << 'EOF'
            # Update package list and install Docker if not already installed
            sudo apt-get update
            sudo apt-get install -y docker.io
            
            # Ensure Docker is running
            sudo systemctl start docker
            sudo systemctl enable docker
            
            # Navigate to the application directory or create if doesn't exist
            mkdir -p /home/ubuntu/frontend-code
            cd /home/ubuntu/frontend-code

            # Clone the latest code from GitHub repository
            if [ -d ".git" ]; then
              git pull origin main
            else
              git clone https://github.com/aashmanarora14/frontend-code .
            fi

            # Build Docker image
            sudo docker build -t my-app-image .

            echo "$DOCKERHUB_TOKEN" | sudo docker login -u "$DOCKERHUB_USERNAME" --password-stdin

            # Correct Docker tag and push
            sudo docker tag my-app-image:latest $DOCKERHUB_USERNAME/my-app-image:latest
            sudo docker push $DOCKERHUB_USERNAME/my-app-image:latest
          EOF
