name: Deploy React App to Ubuntu EC2

on:
  push:
    branches:
      - main  # The branch that triggers the deployment

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20.17.0'

      - name: Install SSH client
        run: sudo apt-get install -y openssh-client

      - name: Add SSH key
        env:
          SSH_PRIVATE_KEY: ${{ secrets.AWS_SSH_PRIVATE_KEY }}
        run: |
          mkdir -p ~/.ssh
          echo "$SSH_PRIVATE_KEY" > ~/.ssh/deploy_key
          chmod 600 ~/.ssh/deploy_key
          ssh-keyscan -H ${{ secrets.AWS_EC2_DNS_NAME }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        env:
          AWS_EC2_USER: ${{ secrets.AWS_EC2_USER }}
          AWS_EC2_DNS_NAME: ${{ secrets.AWS_EC2_DNS_NAME }}
        run: |
          ssh -i ~/.ssh/deploy_key $AWS_EC2_USER@$AWS_EC2_DNS_NAME << 'EOF'
          # Ensure the deployment directory exists
          mkdir -p /home/ubuntu/frontend-code || exit
          
          # Change to the deployment directory
          cd /home/ubuntu/frontend-code || exit

          # Fix ownership and permissions
          sudo chown -R $AWS_EC2_USER:$AWS_EC2_USER /home/ubuntu/frontend-code || exit
          sudo chmod -R u+rwX /home/ubuntu/frontend-code || exit

          # Configure Git to handle permissions issues
          git config --global --add safe.directory /home/ubuntu/frontend-code || exit

          # Pull the latest code
          git pull origin main || exit

          # Install dependencies and build the project
          npm install || exit
          npm run build || exit

          # Install PM2 if not already installed
          if ! command -v pm2 &> /dev/null
          then
              npm install pm2@latest -g
          fi

          # Stop and restart the PM2 process
          pm2 delete react || exit
          pm2 start npm --name "react" -- start || exit
          pm2 restart react || exit

          # Save PM2 process list to be resurrected after reboot
          pm2 save || exit
          EOF
